inherit_from: .rubocop_todo.yml

require: 
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable

Layout/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
