require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  UseCache: true
  SuggestExtensions: true
  CacheRootDirectory: "tmp/rubocop_cache"
  TargetRubyVersion: 3.0

Layout/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
