inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  NewCops: enable

Layout/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
